### ISSUE TITLE
Giftcards not subtracted from order when using new DPD delivery methods

### ISSUE THREAD

**Issue by GioDeGruyter** [dpdconnect/magento2-shipping#67] opened 2023-02-26 13:19 UTC
Hi,

We are using this extension for a client of us. Since changing from the deprecated delivery methods for DPD to the new DPD Home delivery method it is impossible to complete an order with a gift card. I've reproduced the issue on a clean Magento instance with sample data to make sure it wasn't an issue related to any custom code in our project.

Steps to reproduce:
1. DPD home enabled as delivery method:
![image](https://user-images.githubusercontent.com/54057125/221412003-02243a84-d850-4734-b28a-691bc4ba4ec2.png)
2. add an item to the cart and add a giftcard on the cart page:
![image](https://user-images.githubusercontent.com/54057125/221412128-b2ee80a0-36f3-4296-b0b2-be9664b1c4c8.png)
3. Proceed to the checkout and Select DPD Home (classic) as shipping method
4. The gift card is removed from the order summary:
![image](https://user-images.githubusercontent.com/54057125/221412912-f5cf6b99-5e18-4bd5-8173-ec6cdb55b725.png)
5. Place order (gift card is not used when the order is placed, client has to pay the full amount):
![image](https://user-images.githubusercontent.com/54057125/221412354-62f98683-15bf-4d9a-955c-8f4f10ec46e5.png)

Some things we noticed:
* When using the old DPD shipping methods there is no issue. Gift cards are subtracted correctly and the client pays the correct amount
* When any of the new DPD methods is enabled the gift card is removed from the checkout summary for any selected shipping method in the checkout (f.e. table, flat, ...). However the the order is created & completed successfully with the gift card amount subtracted from the order for any other shipping method used which is not one of the new DPD methods.

**Comment by dpdplugin** [comment] 2023-02-27 09:43
Hi @GioDeGruyter ,

Thank you for reporting this issue, what version of Magento do you use?

**Comment by GioDeGruyter** [comment] 2023-02-27 10:24
Hi @dpdplugin,

2.4.5-p1

**Comment by GioDeGruyter** [comment] 2023-03-08 09:54
@dpdplugin Any updates?

**Comment by GioDeGruyter** [comment] 2023-03-14 21:25
@dpdplugin Another week has passed, any updates yet pls?

**Comment by dpdplugin** [comment] 2023-03-22 08:52
Hi @GioDeGruyter ,
Our goal is to release an update next week where this issue should be fixed.

**Comment by dpdplugin** [comment] 2023-03-30 09:55
Hi @GioDeGruyter ,

We are not able to reproduce this issue, are you using the latest version of the plugin?
See as following.
1.
![Screenshot 2023-03-30 at 11 51 15](https://user-images.githubusercontent.com/32730624/228799129-30c6ae45-fe27-4a48-8ed1-7fb5b3269a6b.png)
2.
![Screenshot 2023-03-30 at 11 47 51](https://user-images.githubusercontent.com/32730624/228799253-9972cb54-2d74-4d14-9612-d6bbe93ce2de.png)
3.
![Screenshot 2023-03-30 at 11 50 32](https://user-images.githubusercontent.com/32730624/228799408-abc77339-ddd9-495c-9bee-72191764450a.png)
4.
![Screenshot 2023-03-30 at 11 50 52](https://user-images.githubusercontent.com/32730624/228799480-d5709905-4082-4490-92c5-1f72d7962094.png)

Did you try doing this on a clean install, maybe there is another module doing something.
Alternativly you can contact us at support@x-interactive.nl and we can have a look at your environment.

**Comment by GioDeGruyter** [comment] 2023-03-30 10:14
Hi @dpdplugin ,

As stated in the initial description, I've reproduced this on a clean Magento installation with the latest plugin version installed. I can see in your screenshots that you've tried reproducing this by adding a voucher, but the problem occurs with the use of a gift card, not a voucher.

**Comment by dpdplugin** [comment] 2023-03-30 10:40
Hi @GioDeGruyter ,

Do you use Adobe Commerce or Magento open source?
Gift cards are not a default functionality of open source, or do you use a module for this?

**Comment by GioDeGruyter** [comment] 2023-03-30 10:43
Hi @dpdplugin,

Adobe commerce. No 3rd party modules are installed except for the DPD module on the clean installation.

**Comment by dpdplugin** [comment] 2023-03-30 10:49
Hi @GioDeGruyter ,

Aha that explains, most merchants call cart rules gift cards ;-).
Could you contact us at support@x-interactive.nl so we can discuss how to resolve this.

**Closed by dpdplugin** 2023-03-30 10:49 UTC
